[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
parquet = "54.0.0"
rustls = "0.23.20"
serde = "1.0.217"
serde_json = "1.0.134"
tokio = "1.42.0"
warp = "0.3.7"

